---
- name: "Install Nextcloud Prerequisites."
  package:
    name: "{{ nextcloud_prerequisites }}"
    state: present
  notify: restart webserver {{ webserver_name }}

- name: "Install optional Prerequisites."
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nextcloud_prerequisites_opt }}"
  when: nextcloud_enable_opt_prerequisites | bool
  notify: restart webserver {{ webserver_name }}
  ignore_errors: 'yes'

- name: "Download Nextcloud Hashes."
  get_url:
    url: "{{ item.url }}"
    dest: /tmp/nextcloud-{{ nextcloud_version }}.tar.bz2.{{ item.hash }}
  with_items: "{{ nextcloud_hashes }}"

- name: "Download Nextcloud Package."
  get_url:
    url: "{{ nextcloud_download_url }}"
    dest: /tmp/nextcloud-{{ nextcloud_version }}.tar.bz2

- name: "Verify Nextcloud Package."
  command: "{{ item.hash }}sum -c /tmp/nextcloud-{{ nextcloud_version }}.tar.bz2.{{ item.hash }}"
  args:
    chdir: /tmp/
  with_items: "{{ nextcloud_hashes }}"

- name: "Unpack the Nextcloud Archive."
  unarchive:
    src: /tmp/nextcloud-{{ nextcloud_version }}.tar.bz2
    dest: /var/www/
    remote_src: 'yes'
    owner: "{{ apache2_http_user }}"
    group: "{{ apache2_http_user }}"
    mode: 0750
    keep_newer: 'yes'
    creates: /var/www/nextcloud

- name: "Move the Nextcloud Installation into Place."
  command: mv /var/www/nextcloud "{{ nextcloud_web_dir }}"
  args:
    creates: "{{ nextcloud_web_dir }}"
    warn: 'false'
  when: nextcloud_web_dir != "/var/www/nextcloud"

- name: "Create Nextcloud Data Directory."
  file:
    path: "{{ nextcloud_data_dir }}"
    state: directory
    owner: "{{ apache2_http_user }}"
    group: "{{ apache2_http_user }}"
    mode: 0750
    recurse: 'yes'

- name: "Create Nextcloud Scripts Directory."
  file:
    path: "{{ nextcloud_scripts_dir }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: "Copy the Nextcloud Scripts."
  template:
    src: "{{ item }}"
    dest: "{{ nextcloud_scripts_dir }}/{{ item }}"
    mode: 0750
    owner: root
    group: root
  with_items:
    - nextcloud_set_secure_dir_perms.sh
    - nextcloud_set_update_dir_perms.sh

- name: "Update Permissions."
  shell: "bash {{ nextcloud_scripts_dir }}/nextcloud_set_update_dir_perms.sh"
  args:
    chdir: "{{ nextcloud_scripts_dir }}"
    executable: /bin/bash

- name: "Install Nextcloud via OCC."
  shell: sudo -u "{{ apache2_http_user }}" php "{{ nextcloud_web_dir }}"/occ maintenance:install --database "{{ nextcloud_db_system }}" --database-host "{{ nextcloud_db_host }}" --database-name "{{ nextcloud_db_name }}" --database-user "{{ mysql_root_username }}" --database-pass "{{ mysql_root_password }}" --admin-user "{{ nextcloud_admin_name }}" --admin-pass "{{ nextcloud_admin_pw }}" --data-dir "{{ nextcloud_data_dir }}" --no-interaction
  args:
    chdir: "{{ nextcloud_web_dir }}"
    executable: /bin/bash
  notify: secure permissions
