---
- name: secure permissions
  shell: "{{ nextcloud_scripts_dir }}/nextcloud_set_secure_dir_perms.sh"
  args:
    chdir: "{{ nextcloud_scripts_dir }}"
    executable: /bin/bash

- name: nextcloud maintenance repair
  shell: "sudo -u {{ apache2_http_user }} php {{ nextcloud_web_dir }}/occ maintenance:repair -n"
  args:
    executable: /bin/bash
    chdir: "{{ nextcloud_web_dir }}"

- name: nextcloud maintenance htaccess
  shell: "sudo -u {{ apache2_http_user }} php {{ nextcloud_web_dir }}/occ maintenance:update:htaccess -n"
  args:
    executable: /bin/bash
    chdir: "{{ nextcloud_web_dir }}"

- name: restart coturn
  service:
    name: coturn
    state: restarted
    enabled: 'yes'

- name: print turn secret
  debug:
    msg: "Your TURN secret is <{{ nextcloud_turn_secret }}> - Make sure to put that in your inventory!"
